title: AS-8X API Documentation
baseurl: "/Just-The-Docs-Test"
remote_theme: "just-the-docs/just-the-docs"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Navigation structure
nav_sort: case_insensitive # keeps nav alphabetically sorted

color_scheme: light
footer_content: "AS-8X API Documentation"

aux_links:
  "GitHub Repo":
    - "https://github.com/armsoft/as8x-docs"
aux_links_new_tab: true

enable_copy_code_button: true
